// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	AccountID int64              `json:"account_id"`
	Balance   int64              `json:"balance"`
	Currency  string             `json:"currency"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Transaction struct {
	ID                   int64              `json:"id"`
	SourceAccountID      int64              `json:"source_account_id"`
	DestinationAccountID int64              `json:"destination_account_id"`
	Amount               int64              `json:"amount"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}
